from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from repo_agent.agents.analyzer_agent import AnalyzerAgent
from repo_agent.cache import RepoProfileStore, ReportStore
from repo_agent.investigation import InvestigationTask, Observation, SubInvestigationReport
from repo_agent.llm.schemas import LLMResponse
from repo_agent.runtime.session import AgentSession


class _FakeLLMClient:
    def __init__(self, responses: list[str]) -> None:
        self.responses = list(responses)
        self.calls: list[dict[str, Any]] = []

    def chat(self, **kwargs: Any) -> LLMResponse:
        self.calls.append(kwargs)
        if not self.responses:
            raise AssertionError("No more fake LLM responses configured")
        return LLMResponse(content=self.responses.pop(0))

    @staticmethod
    def extract_json_object(content: str, **_: Any) -> dict[str, Any]:
        return json.loads(content)


class _FakeInvestigator:
    def __init__(self, subreports: list[SubInvestigationReport]) -> None:
        self.subreports = list(subreports)
        self.summarize_calls: list[dict[str, str]] = []
        self.subtasks: list[Any] = []

    def summarize_repo(
        self,
        *,
        user_query: str,
        task: str,
        max_ask_file_calls: int | None = None,
    ) -> str:
        self.summarize_calls.append(
            {
                "user_query": user_query,
                "task": task,
                "max_ask_file_calls": max_ask_file_calls,
            }
        )
        return "# Repo Profile\n\nGenerated by investigator."

    def investigate_subtask(self, subtask: Any) -> SubInvestigationReport:
        self.subtasks.append(subtask)
        if not self.subreports:
            raise AssertionError("No more fake subreports configured")
        return self.subreports.pop(0)


def test_analyzer_uses_cached_profile_and_saves_synthesized_report(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    profile_store = RepoProfileStore(repo)
    report_store = ReportStore(repo)
    profile_store.save("# Repo Profile\n\nCached architecture notes.")

    llm_client = _FakeLLMClient(
        [
            json.dumps(
                {
                    "goal": "Understand the execution flow.",
                    "subquestions": [
                        {
                            "question": "Where is the task executed?",
                            "purpose": "Identify the execution path.",
                            "expected_evidence": ["definition and call site"],
                            "known_information": "Search for execute_task.",
                            "max_tool_calls": 5,
                            "max_files": 2,
                            "max_ask_file_calls": 8,
                        }
                    ],
                    "synthesis_strategy": "Use the subreport answer and cite its observations.",
                }
            ),
            json.dumps(
                {
                    "summary": "The task is executed through worker.py.",
                    "remaining_questions": ["Need to inspect retry behavior."],
                    "profile_update_summary": "None",
                }
            ),
        ]
    )
    investigator = _FakeInvestigator(
        [
            SubInvestigationReport(
                id="S1-report",
                parent_task_id="T1",
                subtask_id="T1-S1",
                question="Where is the task executed?",
                answer="worker.py defines and calls execute_task.",
                confidence="high",
                observations=[
                    Observation(
                        id=9,
                        summary="worker.py defines and calls execute_task.",
                        file_path="worker.py",
                        start_line=1,
                        end_line=4,
                        excerpt="1 | def execute_task():",
                    )
                ],
                files_checked=["worker.py"],
                unresolved=["Need to inspect error handling."],
            )
        ]
    )
    session = AgentSession()
    task = InvestigationTask(
        id="T1",
        user_query="How does execution work?",
        task="Investigate execution flow",
    )
    analyzer = AnalyzerAgent(
        llm_client=llm_client,  # type: ignore[arg-type]
        session=session,
        repo_path=repo,
        investigator=investigator,  # type: ignore[arg-type]
        profile_store=profile_store,
        report_store=report_store,
    )

    report = analyzer.investigate(task)

    assert investigator.summarize_calls == []
    assert session.repo_profile == "# Repo Profile\n\nCached architecture notes.\n"
    assert investigator.subtasks[0].id == "T1-S1"
    assert investigator.subtasks[0].known_information == "Search for execute_task."
    assert investigator.subtasks[0].max_ask_file_calls == 8
    assert report.id == "R-T1"
    assert report.summary == "The task is executed through worker.py."
    assert report.files_checked == ["worker.py"]
    assert report.observations[0].id == 1
    assert report.remaining_questions == [
        "Need to inspect retry behavior.",
        "Need to inspect error handling.",
    ]
    assert session.reports == [report]
    assert len(report_store.list_reports()) == 1
    assert "The task is executed through worker.py." in report_store.load_recent(limit=1)[0]


def test_analyzer_generates_missing_profile_and_rewrites_when_report_suggests_update(
    tmp_path: Path,
) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    profile_store = RepoProfileStore(repo)
    report_store = ReportStore(repo)
    llm_client = _FakeLLMClient(
        [
            json.dumps(
                {
                    "goal": "Check implemented agent roles.",
                    "subquestions": [
                        {
                            "question": "Which agent owns direct repo inspection?",
                            "purpose": "Validate role boundaries.",
                            "expected_evidence": ["agent method evidence"],
                            "known_information": "Search around InvestigatorAgent.",
                            "max_tool_calls": 4,
                            "max_files": 3,
                            "max_ask_file_calls": 12,
                        }
                    ],
                    "synthesis_strategy": "Compare the subreport with the profile.",
                }
            ),
            json.dumps(
                {
                    "summary": "InvestigatorAgent owns direct repo inspection.",
                    "remaining_questions": [],
                    "profile_update_summary": "Mention that InvestigatorAgent is implemented.",
                }
            ),
            "# Repo Profile\n\nUpdated with implemented InvestigatorAgent role.",
        ]
    )
    investigator = _FakeInvestigator(
        [
            SubInvestigationReport(
                id="T2-S1-report",
                parent_task_id="T2",
                subtask_id="T2-S1",
                question="Which agent owns direct repo inspection?",
                answer="InvestigatorAgent owns direct repo inspection.",
                confidence="high",
                files_checked=["src/repo_agent/agents/investigator_agent.py"],
                profile_update_suggestion="The profile should mention the implemented investigator role.",
            )
        ]
    )
    session = AgentSession()
    analyzer = AnalyzerAgent(
        llm_client=llm_client,  # type: ignore[arg-type]
        session=session,
        repo_path=repo,
        investigator=investigator,  # type: ignore[arg-type]
        profile_store=profile_store,
        report_store=report_store,
    )

    report = analyzer.investigate(
        InvestigationTask(
            id="T2",
            user_query="Which parts are implemented?",
            task="Investigate implemented agent roles",
        )
    )

    assert investigator.summarize_calls == [
        {
            "user_query": "Which parts are implemented?",
            "task": "Investigate implemented agent roles",
            "max_ask_file_calls": 40,
        }
    ]
    assert profile_store.load() == "# Repo Profile\n\nUpdated with implemented InvestigatorAgent role.\n"
    assert session.repo_profile == "# Repo Profile\n\nUpdated with implemented InvestigatorAgent role."
    assert report.profile_update_summary == "Mention that InvestigatorAgent is implemented."
    assert len(llm_client.calls) == 3
    assert "Existing RepoProfile" in llm_client.calls[2]["messages"][1]["content"]


def test_analyzer_rejects_empty_plan(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    profile_store = RepoProfileStore(repo)
    profile_store.save("# Repo Profile\n\nCached.")
    analyzer = AnalyzerAgent(
        llm_client=_FakeLLMClient(
            [
                json.dumps(
                    {
                        "goal": "No useful work.",
                        "subquestions": [],
                        "synthesis_strategy": "None",
                    }
                )
            ]
        ),  # type: ignore[arg-type]
        session=AgentSession(),
        repo_path=repo,
        investigator=_FakeInvestigator([]),  # type: ignore[arg-type]
        profile_store=profile_store,
        report_store=ReportStore(repo),
    )

    with pytest.raises(RuntimeError, match="empty analysis plan"):
        analyzer.investigate(
            InvestigationTask(
                id="T3",
                user_query="What now?",
                task="Make an empty plan fail",
            )
        )


def test_analyzer_rejects_ask_file_budget_below_three_times_read_file_budget(
    tmp_path: Path,
) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    profile_store = RepoProfileStore(repo)
    profile_store.save("# Repo Profile\n\nCached.")
    analyzer = AnalyzerAgent(
        llm_client=_FakeLLMClient(
            [
                json.dumps(
                    {
                        "goal": "Budget should fail.",
                        "subquestions": [
                            {
                                "question": "What is implemented?",
                                "purpose": "Check budget validation.",
                                "expected_evidence": ["file status"],
                                "known_information": "Search implemented files.",
                                "max_tool_calls": 4,
                                "max_files": 3,
                                "max_ask_file_calls": 8,
                            }
                        ],
                        "synthesis_strategy": "None",
                    }
                )
            ]
        ),  # type: ignore[arg-type]
        session=AgentSession(),
        repo_path=repo,
        investigator=_FakeInvestigator([]),  # type: ignore[arg-type]
        profile_store=profile_store,
        report_store=ReportStore(repo),
    )

    with pytest.raises(RuntimeError, match="below 3x max_files"):
        analyzer.investigate(
            InvestigationTask(
                id="T4",
                user_query="What now?",
                task="Make a weak ask_file budget fail",
            )
        )
